### PR TITLE
Frontend!

### PR DESCRIPTION
**Pull request by ArthurCueio**
- Added error and info messages.
- Rebased and squashed in one commit because it was getting messy.

Sorry for all the trouble, this should get the job done. But anyway, thanks @suryasr007 for letting me develop this I learned a lot.

### CODE REVIEW

**Comment by suryasr007** [comment]
Thanks. I will look into it.

**Comment by suryasr007** [comment]
@ArthurCueio 

Thanks for the pull request. I just want to know update on following points:
1) Front end for "Generate a custom password from given characters". 
2) Front end for "Generate a non duplicate password".

**Comment by ArthurCueio** [comment]
Hey @suryasr007 

Sorry, I got so excited when this was done that I forgot about the other functions of the API. But I think those should be easy since I have the main one done. I'll start working on it now.

**Comment by ArthurCueio** [comment]
>     1. Front end for "Generate a custom password from given characters".
> 
>     2. Front end for "Generate a non duplicate password".

Added both :+1:

**Comment by suryasr007** [comment]
Hi @ArthurCueio 

Thanks for the efforts you put in. I have few suggestions:
**Template**:
 *  Instead of "Choose a type of password to generate:", provide navigation bar, which displays all the types of password. It will be easy for navigation.
 *  NonDuplicatePassword accepts only 'maxlen'. It doesn't accept other parameters.
 * There are alignment issues in 'more options' of NonDuplicatePassword.
 * Use Bootstrap if possible, lot customaizations and validations are already available.

**File Structure**
Can you put all the frontend functions, in different file? It improves readability of the code. 

Best Suggestion 😅😅
The whole project is already available as API. You can find the API link and endpoints in readme. using AJAX or javascript *fetch* function, you can make your own indepedent frontend project. The other advantage is that, you don't need to validate each field, as backend already provides errors.

**Comment by ArthurCueio** [comment]
Hey,

> - There are alignment issues in 'more options' of NonDuplicatePassword.

This didn't happen on my PC. I'll try testing it on different browsers.

**About the suggestions:**
I don't know why I didn't think of using AJAX earlier :sweat_smile: I'll rewrite the frontend using that.

> Use Bootstrap if possible, lot customaizations and validations are already available.

It's alredy using Bootstrap, just some small tweaks that I had to do with CSS. But again: I'll try it on different browsers to make sure.

And again: Thanks for letting me do this. I learned a lot since I started.

**Comment by ArthurCueio** [comment]
- I found that it wasn't being rendered right in Google Chrome. Corrected that and it should look right in most browsers now.
- Rewrote using JQuery.

Look at the `parseExcludeChars` function in `main.js` you could implement something like that in the API to avoid having multiple parameters to exclude chars.

**Comment by suryasr007** [comment]
Hi @ArthurCueio 

I couldn't able to find any navigation bar. It will be difficult for user to navigate from type of password to another type.

Something like this:
image

**Comment by ArthurCueio** [comment]
I added that just above the generator. Using bootstrap to change between the types and keeping everything in the same page.
screenshot_2019-01-14_12-14-40

I think it works best this way, but I can put it on the top of the page if you want.

**Comment by suryasr007** [comment]
Yes @ArthurCueio . 

This is what intended.

**Comment by ArthurCueio** [comment]
> I couldn't able to find any navigation bar. It will be difficult for user to navigate from type of password to another type.

But that navbar is alredy in the `Rewrote using JQuery ` commit. Sometimes you may need to restart the api or clear the cache for some changes to show. (SHIFT + F5 on some browsers)

**Comment by suryasr007** [comment]
Will check and update you.

**Comment by suryasr007** [comment]
@ArthurCueio .

The front-end looks good. 

Only few suggestions from my end. 
  *  "From given characters" tab. Raise an error if the characters field is empty
  * Can you make the size of the container uniform across different types of password?
  * Can you make it colorful?

**Comment by ArthurCueio** [comment]
> 
>     * "From given characters" tab. Raise an error if the characters field is empty
> 
>     * Can you make the size of the container uniform across different types of password?
> 

Yes, of course. I'll work on that

>     * Can you make it colorful?

I'm not so good with colors but I'll try to make something.

**Comment by ArthurCueio** [comment]
hi @suryasr007 

I changed the button color and added the error message in case the char input is empty.

>
> * Can you make the size of the container uniform across different types of password?
>

I tried that but it leaves a ugly white space even with the form centered in it.

>
> * Can you make it colorful?
>

I made the generate button blue and outlined.  Just that gave the page a less grey-ish look. I tried changing the header's color or the background of it, but everything I tried draw attention away from the generator.

**Comment by suryasr007** [comment]
Thanks @ArthurCueio 

It Looks good.

**Pull request merged**
