### PR TITLE
Added: Frontend

### PR DESCRIPTION
**Pull request by ArthurCueio**
**Added frontend with:**

- Generate button.
- Options for minimum length, max. length, etc...
- Footer with credits and link to Gh project.

**Bonus:**

- Reformated api.py using PyCharm (PEP 8 coding style)

Fixes: #6

### CODE REVIEW

**Comment by suryasr007** [comment]
Hi @ArthurCueio

The front end seems good. 

Few thoughts from my end:
1. Please enable route for '/api/v1' route. It can be used to integrate with other applications.
2. Adding fields for excluding characters, numbers and special characters would be beneficial as this feature is already available.
3. You can directly use 'POST' method on '/' path, instead of /g.

Thanks
Surya Teja Reddy V

**Comment by ArthurCueio** [comment]
Hey @suryasr007 

I added this:
> 2. Adding fields for excluding characters, numbers and special characters would be beneficial as this feature is already available.

and fixed this:

> 3. You can directly use 'POST' method on '/' path, instead of /g.

Now I got confused in using '/api' to generate the passwords. Should I just use a normal GET request do to that or is there a fancy way to do it inside flask?

I couldn't find anything like it in the docs of flask and flask restful.

**Comment by suryasr007** [comment]
Hi @ArthurCueio 

I couldn't able to find fields for excluding characters, numbers and special characters:

image


For '/api', I mean to tell is that, '/' will show GUI interface and '/api' will take care of API. Anyway, I will take care of '/api'.

**Comment by ArthurCueio** [comment]
> For '/api', I mean to tell is that, '/' will show GUI interface and '/api' will take care of API. Anyway, I will take care of '/api'.

Ooh. Sorry I think you meant something like a page talking about the API. Anyway I'll push this changes:

> I couldn't able to find fields for excluding characters, numbers and special characters:

And you can deal with the '/api'

**Comment by suryasr007** [comment]
Thanks @ArthurCueio 

I will look into it.

**Pull request merged**
